/**
 * Database -> TypeScript mappers for the star-app PocketBase schema.
 *
 * The schema is generated by `db/pocketbase/schema.py` and is snake_case. These
 * mappers adapt its columns to the app types in `src/core/types.ts`.
 *
 * Column names that matter (and have drifted before):
 *   menu_items.image_url   -> MenuItem.image
 *   menu_items.is_available-> MenuItem.soldOut (inverted)
 *   restaurant_tables      -> RestaurantTable (never `tables`)
 *   restaurant_settings.data blob -> extra AppSkinSettings keys
 */
import type {
  AppSkinSettings,
  BillRequest,
  DiningSession,
  MenuItem,
  Order,
  OrderStatus,
  PromoItem,
  RestaurantTable,
  VisitorRecord,
} from '../../core/types';

export type RawRecord = Record<string, unknown> & { id: string };

// ── Value coercion ───────────────────────────────────────────────────────────

const asNumber = (value: unknown, fallback = 0): number => {
  if (typeof value === 'number' && Number.isFinite(value)) return value;
  if (typeof value === 'string') {
    const parsed = Number(value);
    return Number.isFinite(parsed) ? parsed : fallback;
  }
  return fallback;
};

const asOptionalNumber = (value: unknown): number | undefined =>
  value === undefined || value === null ? undefined : asNumber(value);

const asString = (value: unknown, fallback = ''): string =>
  typeof value === 'string' ? value : fallback;

const asOptionalString = (value: unknown): string | undefined =>
  value === undefined || value === null ? undefined : asString(value);

const asBoolean = (value: unknown, fallback = false): boolean => {
  if (typeof value === 'boolean') return value;
  if (typeof value === 'string') return value.toLowerCase() === 'true';
  if (typeof value === 'number') return value !== 0;
  return fallback;
};

const asJson = <T>(value: unknown, fallback: T): T => {
  if (value === undefined || value === null) return fallback;
  if (typeof value === 'string') {
    try {
      return JSON.parse(value) as T;
    } catch {
      return fallback;
    }
  }
  if (typeof value === 'object') return value as T;
  return fallback;
};

const asStringArray = (value: unknown): string[] => {
  const parsed = asJson<unknown>(value, []);
  return Array.isArray(parsed) ? parsed.map((entry) => String(entry)) : [];
};

/** Drop undefined entries so a partial update never sends `field: undefined`. */
export const compact = (record: Record<string, unknown>): Record<string, unknown> => {
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(record)) {
    if (value !== undefined) out[key] = value;
  }
  return out;
};

// ── Menu items ───────────────────────────────────────────────────────────────

export const toMenuItem = (record: RawRecord): MenuItem => ({
  id: record.id,
  restaurant_id: asOptionalString(record.restaurant_id),
  name: asString(record.name),
  description: asString(record.description),
  price: asNumber(record.price),
  category: (asString(record.category) || 'pasteles') as MenuItem['category'],
  /** DB column: image_url */
  image: asString(record.image_url),
  isWeightBased: asBoolean(record.is_weight_based),
  weightPricePerKg: asOptionalNumber(record.weight_price_per_kg),
  weightInGrams: asOptionalNumber(record.weight_in_grams),
  options: asJson(record.options, undefined),
  strain: asOptionalString(record.strain) as MenuItem['strain'],
  /** DB column: is_available (inverted for soldOut) */
  soldOut: record.is_available === undefined ? undefined : !asBoolean(record.is_available, true),
  stock: asOptionalNumber(record.stock),
  trackInventory: asBoolean(record.track_inventory),
});

export const menuItemToDb = (item: Partial<MenuItem>): Record<string, unknown> =>
  compact({
    restaurant_id: item.restaurant_id,
    name: item.name,
    description: item.description,
    price: item.price,
    category: item.category,
    image_url: item.image,
    is_weight_based: item.isWeightBased,
    weight_price_per_kg: item.weightPricePerKg,
    weight_in_grams: item.weightInGrams,
    options: item.options,
    strain: item.strain,
    is_available: item.soldOut === undefined ? undefined : !item.soldOut,
    stock: item.stock,
    track_inventory: item.trackInventory,
  });

// ── Promos ───────────────────────────────────────────────────────────────────

export const toPromoItem = (record: RawRecord): PromoItem => ({
  ...toMenuItem(record),
  category: 'promo',
  active: asBoolean(record.active),
  bundleItems: asJson(record.bundle_items, undefined),
  discountType: asOptionalString(record.discount_type) as PromoItem['discountType'],
  discountValue: asOptionalNumber(record.discount_value),
  originalPrice: asOptionalNumber(record.original_price),
});

// ── Orders ───────────────────────────────────────────────────────────────────

export const toOrder = (record: RawRecord): Order => {
  const status = asString(record.status, 'recibido') as OrderStatus;
  const rawItems = Array.isArray(record.items) ? record.items : [];

  return {
    id: record.id,
    collectionId: asOptionalString(record.collectionId),
    collectionName: asOptionalString(record.collectionName) ?? 'orders',
    restaurant_id: asOptionalString(record.restaurant_id),
    table_id: asOptionalString(record.table_id),
    customerName: asString(record.customer_name),
    customerAddress: asString(record.customer_address),
    items: rawItems as Order['items'],
    total: asNumber(record.total),
    subtotal: asOptionalNumber(record.subtotal),
    tax: asOptionalNumber(record.tax),
    deliveryFee: asOptionalNumber(record.delivery_fee),
    status,
    paymentMethod: asString(record.payment_method, 'efectivo') as Order['paymentMethod'],
    payWithAmount: asOptionalNumber(record.pay_with_amount),
    transferScreenshot: asOptionalString(record.transfer_screenshot),
    deliveryDistanceKm: asOptionalNumber(record.delivery_distance_km),
    order_type: asOptionalString(record.order_type) as Order['order_type'],
    notes: asOptionalString(record.notes),
    sessionId: asOptionalString(record.session_id),
    timestamp: asNumber(record.timestamp, Date.now()),
    statusTimestamps: asJson<Order['statusTimestamps']>(record.status_timestamps, {}),
  };
};

/**
 * Fields a client may send when creating an order.
 *
 * `status`, `total`, `subtotal`, `tax`, `timestamp`, `status_timestamps` and the
 * station fields are deliberately NOT sent: the PocketBase hook
 * (`db/pocketbase/pb_hooks/star_security.pb.js`) recomputes/owns them, and a
 * client-supplied value would be ignored at best and a forged `status: "paid"`
 * at worst. The order returned from `create()` carries the server values.
 */
export const orderToDb = (order: Omit<Order, 'id'> & { id?: string }): Record<string, unknown> =>
  compact({
    restaurant_id: order.restaurant_id,
    table_id: order.table_id,
    customer_name: order.customerName || '',
    customer_address: order.customerAddress || '',
    items: order.items || [],
    delivery_fee: order.deliveryFee || 0,
    delivery_distance_km: order.deliveryDistanceKm || 0,
    payment_method: order.paymentMethod || 'efectivo',
    pay_with_amount: order.payWithAmount || 0,
    order_type: order.order_type || 'pickup',
    notes: order.notes || '',
    session_id: order.sessionId || '',
    transfer_screenshot: order.transferScreenshot || '',
  });

// ── Restaurant tables ────────────────────────────────────────────────────────

export const toRestaurantTable = (record: RawRecord): RestaurantTable => ({
  id: record.id,
  restaurant_id: asString(record.restaurant_id),
  table_number: asNumber(record.table_number, 0),
  display_name: asOptionalString(record.display_name),
  seats: asNumber(record.seats, 1),
  location: asOptionalString(record.location) as RestaurantTable['location'],
  qr_code_url: asOptionalString(record.qr_code_url),
  x: asOptionalNumber(record.x),
  y: asOptionalNumber(record.y),
  // Floor-plan geometry (spec 006 B1) - written by the manager editor.
  width: asOptionalNumber(record.width),
  height: asOptionalNumber(record.height),
  rotation: asOptionalNumber(record.rotation),
  shape: asOptionalString(record.shape) as RestaurantTable['shape'],
  is_available: record.is_available === undefined ? true : asBoolean(record.is_available, true),
});

export const restaurantTableToDb = (
  table: Partial<RestaurantTable>,
): Record<string, unknown> =>
  compact({
    restaurant_id: table.restaurant_id,
    table_number: table.table_number,
    display_name: table.display_name,
    seats: table.seats,
    location: table.location,
    qr_code_url: table.qr_code_url,
    x: table.x,
    y: table.y,
    width: table.width,
    height: table.height,
    rotation: table.rotation,
    shape: table.shape,
    is_available: table.is_available,
  });

// ── Settings (restaurant + restaurant_settings blob) ─────────────────────────

/**
 * Branding keys live on the `restaurants` row; everything else goes into the
 * `restaurant_settings.data` blob.
 */
export const RESTAURANT_BRANDING_KEYS = [
  'name',
  'currency',
  'tagline',
  'description',
  'logoUrl',
  'heroImageUrl',
  'heroTitle',
  'primaryColor',
  'secondaryColor',
  'accentColor',
  'backgroundColor',
  'googleFontUrl',
  'googleFontName',
  'mode',
] as const;

export const appSkinSettingsToRestaurantFields = (
  settings: Partial<AppSkinSettings>,
): Record<string, unknown> =>
  compact({
    name: settings.name,
    currency: settings.currency,
    tagline: settings.tagline,
    description: settings.description,
    logo_url: settings.logoUrl,
    hero_image_url: settings.heroImageUrl,
    hero_text: settings.heroTitle,
    primary_color: settings.primaryColor,
    secondary_color: settings.secondaryColor,
    accent_color: settings.accentColor,
    background_color: settings.backgroundColor,
    google_font_url: settings.googleFontUrl,
    google_font_name: settings.googleFontName,
    mode: settings.mode,
  });

export const appSkinSettingsToExtraData = (
  settings: Partial<AppSkinSettings>,
): Record<string, unknown> => {
  const branding = new Set<string>(RESTAURANT_BRANDING_KEYS);
  const extra: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(settings)) {
    if (!branding.has(key) && value !== undefined) extra[key] = value;
  }
  return extra;
};

export const toAppSkinSettings = (
  restaurant: RawRecord | null,
  settingsData?: Record<string, unknown> | null,
): AppSkinSettings | null => {
  if (!restaurant) return null;
  return {
    name: asString(restaurant.name),
    currency: asOptionalString(restaurant.currency),
    tagline: asOptionalString(restaurant.tagline),
    description: asOptionalString(restaurant.description),
    logoUrl: asOptionalString(restaurant.logo_url),
    heroImageUrl: asOptionalString(restaurant.hero_image_url),
    heroTitle: asOptionalString(restaurant.hero_text),
    primaryColor: asOptionalString(restaurant.primary_color),
    secondaryColor: asOptionalString(restaurant.secondary_color),
    accentColor: asOptionalString(restaurant.accent_color),
    backgroundColor: asOptionalString(restaurant.background_color),
    googleFontUrl: asOptionalString(restaurant.google_font_url),
    googleFontName: asOptionalString(restaurant.google_font_name),
    mode: asOptionalString(restaurant.mode) as AppSkinSettings['mode'],
    // Extra settings (delivery rules, ui text, categories, ...) from the blob.
    ...(settingsData ?? {}),
  };
};

// ── Dining sessions & bill requests ──────────────────────────────────────────

export const toDiningSession = (record: RawRecord): DiningSession => ({
  id: record.id,
  restaurant_id: asString(record.restaurant_id),
  table_id: asString(record.table_id),
  customer_name: asOptionalString(record.customer_name),
  customer_phone: asOptionalString(record.customer_phone),
  status: asString(record.status, 'active') as DiningSession['status'],
  order_ids: asStringArray(record.order_ids),
  session_start: asNumber(record.session_start, Date.now()),
  session_end: asOptionalNumber(record.session_end),
});

export const diningSessionToDb = (
  session: Partial<DiningSession>,
): Record<string, unknown> =>
  compact({
    restaurant_id: session.restaurant_id,
    table_id: session.table_id,
    customer_name: session.customer_name,
    customer_phone: session.customer_phone,
    status: session.status,
    order_ids: session.order_ids,
    session_start: session.session_start,
    session_end: session.session_end,
  });

export const toBillRequest = (record: RawRecord): BillRequest => ({
  id: record.id,
  restaurant_id: asString(record.restaurant_id),
  table_id: asString(record.table_id),
  order_ids: asStringArray(record.order_ids),
  subtotal: asNumber(record.subtotal),
  tax: asNumber(record.tax),
  tip: asNumber(record.tip),
  total: asNumber(record.total),
  status: asString(record.status, 'requested') as BillRequest['status'],
  payments: asJson(record.payments, []),
  requested_at: asNumber(record.requested_at, Date.now()),
});

export const billRequestToDb = (bill: Partial<BillRequest>): Record<string, unknown> =>
  compact({
    restaurant_id: bill.restaurant_id,
    table_id: bill.table_id,
    order_ids: bill.order_ids,
    subtotal: bill.subtotal,
    tax: bill.tax,
    tip: bill.tip,
    total: bill.total,
    status: bill.status,
    payments: bill.payments,
    requested_at: bill.requested_at,
  });

// ── Visitors ─────────────────────────────────────────────────────────────────

export const toVisitorRecord = (record: RawRecord): VisitorRecord => ({
  id: record.id,
  restaurant_id: asOptionalString(record.restaurant_id),
  ip: asString(record.ip, 'unknown'),
  userAgent: asOptionalString(record.userAgent),
  deviceType: asOptionalString(record.deviceType) as VisitorRecord['deviceType'],
  isPwaInstalled: record.isPwaInstalled === undefined ? undefined : asBoolean(record.isPwaInstalled),
  sessionId: asString(record.sessionId),
  firstVisit: asString(record.first_visit),
  lastVisit: asString(record.last_visit),
  visitCount: asNumber(record.visit_count, 1),
  associatedOrders: asStringArray(record.associated_orders),
});

/**
 * Fields a client may send when creating a visitor row.
 * `first_visit` / `last_visit` / `visit_count` are owned by the PocketBase hook
 * (`onRecordCreateRequest` for `visitors`), so they are never sent.
 */
export const visitorToDb = (visitor: Partial<VisitorRecord>): Record<string, unknown> =>
  compact({
    restaurant_id: visitor.restaurant_id,
    sessionId: visitor.sessionId,
    userAgent: visitor.userAgent,
    deviceType: visitor.deviceType,
    isPwaInstalled: visitor.isPwaInstalled,
    ip: visitor.ip,
  });
